### ISSUE TITLE
Can't initialize Soap12Client - compiler says it's abstract

### ISSUE THREAD

**Issue by BillAtSysco** [ballerina-platform/module-ballerina-soap#79]
**Description:**
Attempting to initialize a Soap12Client results in the error:
"cannot initialize abstract object 'ballerina/soap:1.9.0:Soap12Client'"

**Suggested Labels:**
You tell me

**Suggested Assignees:**
Not my call

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Windows 10
Zulu OpenJDK

**Steps to reproduce:**
try to instantiate a Soap12Client - see below

_**arg.bal**_

    import ballerina/soap;
    public function main() {
       soap:Soap12Client  soapClient = new("https://neversaynever.com/");
    }

_**run arg.bal**_

    C:\whereever\src>ballerina run arg.bal
        Compiling source
              arg.bal
        error: .::arg.bal:3:36: cannot initialize abstract object 'ballerina/soap:1.9.0:Soap12Client'

_**ballerina version**_

    C:\whereever\src>ballerina version
        Ballerina Swan Lake Preview 4
        Language specification v2020-09-22
        Update Tool 0.8.8

_**ballerina/soap version**_
in balo_cache => soap-2020r2-any-1.9.0.balo

**Related Issues:**
It would be nice to able to list all the local modules installed and their versions. But that's not your problem.

**Comment by BillAtSysco** [comment]
This is also true for the Soap11Client

**Comment by Bhashinee** [comment]
Ballerina SOAP connector is only compatible only with Swan Lake Preview1 release. 
This will not be migrated to the latest Ballerina releases as going forward we will not be maintaining this repo. Hence closing the issue.
